blank_issues_enabled: false
contact_links:
  - name: Propose change(s) to SWEET
    url: https://github.com/ESIPFed/sweet/issues
    about: Please contribute code here.
  - name: Ask questions about SWEET
    url: https://github.com/ESIPFed/sweet/issues
    about: Please ask and answer questions here.
  - name: SWEET Slack channel
    url: https://esip-all.slack.com/
    about: Use the 'sweetontology' Slack channel to discuss SWEET
