blank_issues_enabled: false
contact_links:
  - name: SWEET Issue Tracker
    url: https://github.com/ESIPFed/sweet/issues
    about: Please contribute code, ask and answer questions here.
  - name: SWEET Slack channel
    url: https://esip-all.slack.com/
    about: Use the #sweetontology Slack channel to discuss SWEET
