blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/ESIPFed/sweet/issues
    about: Create a bug report to help improve SWEET
  - name: Add feature(s)
    url: https://github.com/ESIPFed/sweet/issues
    about: Suggest a new idea e.g. new class(es) or definition(s) to SWEET
  - name: Propose a SWEET alignment graph
    url: https://github.com/ESIPFed/sweet/issues
    about: Suggest a new graph alignment to harmonize SWEET with other semantic resources
  - name: SWEET Slack channel
    url: https://esip-all.slack.com/
    about: Use the 'sweetontology' Slack channel to discuss SWEET
